import Link from "next/link";
import { ArrowRight, BarChart3, Check, Code, GraduationCap, HelpCircle, MessageSquare, Monitor, QrCode, ShieldCheck, Users, Zap } from "lucide-react";
import type { ReactNode } from "react";

export function QueueSite({ children, signedIn = false }: { children: ReactNode; signedIn?: boolean }) {
  return <div className="min-h-screen bg-slate-50 font-sans text-slate-900 flex flex-col"><QueueHeader signedIn={signedIn} />{children}<QueueFooter /></div>;
}

export function QueueHeader({ signedIn = false }: { signedIn?: boolean }) {
  return <nav className="bg-white border-b border-slate-200 sticky top-0 z-50" aria-label="QueueMaster"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex justify-between h-16 items-center"><Link href="/queue" className="flex items-center gap-2 text-emerald-600 font-bold text-xl tracking-tight"><GraduationCap size={28} aria-hidden="true" /><span>QueueMaster</span></Link><div className="hidden md:flex items-center gap-8 text-sm font-medium text-slate-600"><Link href="/queue/features">Features</Link><Link href="/queue/use-cases">Use Cases</Link><Link href="/queue/pricing">Pricing</Link><Link href="/queue/instructions">Instructions</Link></div>{signedIn ? <details className="relative"><summary className="list-none cursor-pointer bg-slate-900 text-white px-4 py-2 rounded-lg font-medium text-sm">Account</summary><div className="absolute right-0 mt-2 w-44 rounded-xl border border-slate-200 bg-white p-2 shadow-xl"><Link href="/queue/dashboard" className="block rounded-lg px-3 py-2 text-sm hover:bg-slate-100">Dashboard</Link><form action="/auth/signout" method="post"><button className="w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-100">Sign Out</button></form></div></details> : <Link href="/queue/dashboard" className="bg-slate-900 text-white px-4 py-2 rounded-lg font-medium text-sm">Start Free</Link>}</div></div></nav>;
}

export function QueueHome({ signedIn = false }: { signedIn?: boolean }) {
  const cards = [
    { title: "Instant Check-in", text: "Students scan a lobby-specific QR code to enter the queue. No app required.", icon: <QrCode size={32} />, color: "bg-blue-100 text-blue-600" },
    { title: "Smartboard Display", text: "Cast the live queue to your projector. It stays green while a guest is called or being helped.", icon: <Monitor size={32} />, color: "bg-emerald-100 text-emerald-600" },
    { title: "Participation Analytics", text: "A future reporting view will summarize queue activity without changing the live classroom flow.", icon: <BarChart3 size={32} />, color: "bg-purple-100 text-purple-600", soon: true },
  ];
  return <QueueSite signedIn={signedIn}><main><section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 md:py-28 text-center"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-100 text-emerald-800 text-sm font-bold mb-6"><Zap size={16} /> Live multi-lobby pilot</div><h1 className="text-5xl md:text-6xl font-extrabold tracking-tight mb-6">Stop writing names <br />on the whiteboard.</h1><p className="text-xl text-slate-500 max-w-2xl mx-auto mb-10">The quiet, fair, and organized way to manage student questions, office hours, and lab help. Let students stay at their desks while they wait.</p><Link href="/queue/dashboard" className="inline-flex bg-emerald-600 text-white px-8 py-4 rounded-xl font-bold text-lg items-center gap-2 shadow-lg shadow-emerald-200">Create a Classroom Lobby <ArrowRight size={20} /></Link></section><section className="bg-white py-20 border-y border-slate-200"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid md:grid-cols-3 gap-12 text-center">{cards.map((card) => <article key={card.title}><div className={`w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-6 ${card.color}`}>{card.icon}</div><h2 className="text-xl font-bold mb-3">{card.title}{card.soon ? <Soon /> : null}</h2><p className="text-slate-500">{card.text}</p></article>)}</div></section></main></QueueSite>;
}

export function QueueFeatures({ signedIn = false }: { signedIn?: boolean }) {
  return <QueueSite signedIn={signedIn}><main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20"><PageHeading title="Features Built for Educators">Everything in the local pilot, with future features labeled clearly.</PageHeading><div className="space-y-16"><Feature icon={<Monitor size={80} className="text-emerald-500" />} title="Realtime Lobby Views">Guest phones, staff controls, and the classroom display refetch an authorized snapshot whenever the queue changes.</Feature><Feature reverse icon={<BarChart3 size={80} className="text-slate-300" />} title="Participation Analytics"><Soon /> Reporting and CSV exports are not active in this pilot.</Feature><Feature icon={<MessageSquare size={80} className="text-slate-300" />} title="Silent SMS Notifications"><Soon /> QueueMaster does not collect phone numbers or send texts in this pilot.</Feature></div></main></QueueSite>;
}

export function QueueUseCases({ signedIn = false }: { signedIn?: boolean }) {
  const cases = [{ title: "University Office Hours", text: "Let students keep working while instructors and TAs serve a shared, visible queue.", icon: <HelpCircle size={40} className="text-blue-500 mb-4" /> }, { title: "Hackathons", text: "Give every mentor an admin card and route waiting guests to the right helper.", icon: <Code size={40} className="text-emerald-500 mb-4" /> }, { title: "Active Classrooms & Labs", text: "Students enter a desk or car location, then continue working until their screen turns green.", icon: <Users size={40} className="text-purple-500 mb-4" /> }];
  return <QueueSite signedIn={signedIn}><main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20"><PageHeading title="Who uses QueueMaster?">Built for dynamic, active learning environments.</PageHeading><div className="grid md:grid-cols-3 gap-8">{cases.map((item) => <article key={item.title} className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200">{item.icon}<h2 className="text-2xl font-bold mb-3">{item.title}</h2><p className="text-slate-600">{item.text}</p></article>)}</div></main></QueueSite>;
}

export function QueuePricing({ signedIn = false }: { signedIn?: boolean }) {
  return <QueueSite signedIn={signedIn}><main className="py-20"><div className="max-w-7xl mx-auto px-4"><PageHeading title="Simple Pilot Pricing">The current QueueMaster pilot is free to test.</PageHeading><div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto"><PriceCard name="Local Pilot" price="$0" suffix="/pilot" items={["Multiple lobby workflow", "Guest and staff QR codes", "Classroom display", "Owner-managed staff promotion"]} /><PriceCard dark name="QueueMaster Pro" price="—" suffix=" coming later" items={["Participation analytics", "CSV exports", "SMS notifications", "Custom reporting"]} /></div></div></main></QueueSite>;
}

function PriceCard({ dark = false, name, price, suffix, items }: { dark?: boolean; name: string; price: string; suffix: string; items: string[] }) { return <section className={dark ? "bg-slate-900 p-8 rounded-3xl shadow-xl flex flex-col border-2 border-emerald-500" : "bg-white p-8 rounded-3xl border border-slate-200 shadow-sm flex flex-col"}><h2 className={`text-2xl font-bold ${dark ? "text-white" : ""}`}>{name}</h2><div className="mt-4 mb-8"><span className={`text-5xl font-black ${dark ? "text-white" : ""}`}>{price}</span><span className={dark ? "text-slate-400" : "text-slate-500"}>{suffix}</span></div><ul className="space-y-4 mb-8 flex-grow">{items.map((item) => <li key={item} className={`flex items-center gap-3 ${dark ? "text-slate-300" : "text-slate-600"}`}><Check size={20} className="text-emerald-500" />{item}</li>)}</ul>{dark ? <button disabled title="Billing is not included in the local pilot" className="w-full py-4 rounded-xl font-bold text-slate-300 bg-slate-700 cursor-not-allowed">Upgrade to Pro · Coming soon</button> : <Link href="/queue/dashboard" className="w-full py-4 rounded-xl font-bold text-center text-white bg-emerald-600">Start Free</Link>}</section>; }
function Feature({ reverse = false, icon, title, children }: { reverse?: boolean; icon: ReactNode; title: string; children: ReactNode }) { return <section className={`flex flex-col items-center gap-12 ${reverse ? "md:flex-row-reverse" : "md:flex-row"}`}><div className="flex-1 w-full bg-slate-100 rounded-3xl p-8 aspect-video flex items-center justify-center border border-slate-200">{icon}</div><div className="flex-1 space-y-4"><h2 className="text-3xl font-bold">{title}</h2><div className="text-slate-500 text-lg">{children}</div></div></section>; }
function PageHeading({ title, children }: { title: string; children: ReactNode }) { return <div className="text-center mb-16"><h1 className="text-4xl font-extrabold mb-4">{title}</h1><p className="text-xl text-slate-500">{children}</p></div>; }
function Soon() { return <span className="ml-2 inline-flex rounded-full bg-amber-100 px-2 py-1 align-middle text-[10px] font-bold uppercase tracking-wide text-amber-800">Coming soon</span>; }

export function QueueFooter() {
  return <footer className="bg-slate-900 text-slate-400 py-12 mt-auto"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid md:grid-cols-4 gap-8"><div className="md:col-span-2"><div className="flex items-center gap-2 text-white font-bold text-xl mb-4"><GraduationCap size={24} /><span>QueueMaster</span></div><p className="text-sm max-w-md mb-4">Stop writing names on the whiteboard. A focused queue service from Fourth Canal.</p><div className="flex items-center gap-2 text-sm text-slate-500"><ShieldCheck size={16} /> Private guest sessions and server-authorized actions.</div></div><div><h2 className="text-white font-bold mb-4">QueueMaster</h2><ul className="space-y-2 text-sm"><li><Link href="/queue">Home</Link></li><li><Link href="/queue/about">About</Link></li><li><Link href="/queue/instructions">Instructions</Link></li></ul></div><div><h2 className="text-white font-bold mb-4">Help & legal</h2><ul className="space-y-2 text-sm"><li><Link href="/queue/support">Support</Link></li><li><Link href="/queue/privacy">Privacy Policy</Link></li><li><Link href="/queue/terms">Terms of Service</Link></li></ul></div></div><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-12 pt-8 border-t border-slate-800 text-xs leading-relaxed"><p>© {new Date().getFullYear()} QueueMaster by Fourth Canal.</p><p className="mt-3 max-w-4xl">Independent project. Not affiliated with or endorsed by any school or university. QueueMaster is for line coordination only—not emergencies, medical advice, attendance compliance, or protected-record storage.</p></div></footer>;
}
