import Link from "next/link";
import type { ReactNode } from "react";
import { QueueSite } from "./QueueHome";

export function QueueInformationPage({ title, eyebrow, intro, children, signedIn = false }: { title: string; eyebrow: string; intro: string; children: ReactNode; signedIn?: boolean }) {
  return <QueueSite signedIn={signedIn}><main className="w-full max-w-4xl mx-auto px-4 sm:px-6 py-16 md:py-20"><p className="text-emerald-700 text-sm font-bold uppercase tracking-wider mb-3">{eyebrow}</p><h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-4">{title}</h1><p className="text-lg text-slate-500 mb-12 max-w-3xl">{intro}</p><div className="space-y-10 text-slate-700 leading-7 [&_h2]:text-2xl [&_h2]:font-bold [&_h2]:text-slate-900 [&_h2]:mb-3 [&_h3]:text-lg [&_h3]:font-bold [&_h3]:text-slate-900 [&_ul]:list-disc [&_ul]:pl-6 [&_ol]:list-decimal [&_ol]:pl-6 [&_a]:text-emerald-700 [&_a]:underline">{children}</div></main></QueueSite>;
}

export function HowQueueMasterWorks({ signedIn = false }: { signedIn?: boolean }) {
  return <QueueInformationPage signedIn={signedIn} eyebrow="QueueMaster workflow" title="How it works" intro="Each lobby has separate guest and staff entry points. Every view includes a clear route back to the dashboard or lobby controls.">
    <section><h2>Lobby owner</h2><ol><li>Sign in with Google and open the <Link href="/queue/dashboard">QueueMaster dashboard</Link>.</li><li>Create a lobby, then share its guest QR with people who need help and its owner-only staff QR with potential helpers.</li><li>Open Admin controls, turn on Accepting guests, and remain online through the automatic 20-second heartbeat.</li><li>Watch the signed-in staff pool, send an in-app admin request, and wait for that person to accept or decline.</li><li>Manage staff, waiting guests, reassignment, and the classroom display. Staff with active guests cannot be removed until every waiting, called, and helping guest is reassigned.</li></ol></section>
    <section><h2>Guest</h2><ol><li>Scan the guest QR. No account is required.</li><li>Select an online admin who is accepting guests, enter only a first name and desk/car location, then check in.</li><li>Keep the page open or return later in the same browser. The private guest cookie restores the active lobby.</li><li>The screen turns green when called and stays green while helping.</li><li>Start helping or finish from the guest page when appropriate, or leave before being called.</li></ol></section>
    <section><h2>Staff candidate</h2><ol><li>Scan the owner-only staff QR and sign in with Google.</li><li>Explicitly join the lobby staff pool. QueueMaster shows the owner your Google name and email inside that lobby only.</li><li>Stay online through the 20-second heartbeat while waiting.</li><li>Accept or decline the owner&apos;s in-app request from the staff page or dashboard. Requests expire after 24 hours.</li><li>After acceptance, QueueMaster redirects to Admin controls with Accepting guests turned off until you enable it.</li></ol></section>
    <section><h2>Admin</h2><ol><li>Enable Accepting guests when ready.</li><li>Call the next assigned guest. Guest and display screens turn green.</li><li>Start helping, then finish the session or mark a called guest as no-show.</li><li>Reorder, cancel, or reassign waiting guests within the permissions shown in Admin controls.</li></ol></section>
    <section><h2>Classroom display</h2><p>The read-only display shows staff state, each active green session, the approved public waiting fields, and the guest QR. Exit display returns to the lobby controls instead of relying on browser history.</p></section>
    <section><h2>Offline behavior</h2><p>An admin becomes effectively offline 45 seconds after the last heartbeat. New guests cannot choose that admin, but existing waiting and active entries stay in place until the owner manually reassigns them.</p></section>
  </QueueInformationPage>;
}

export function QueuePrivacy({ signedIn = false }: { signedIn?: boolean }) {
  return <QueueInformationPage signedIn={signedIn} eyebrow="Legal" title="QueueMaster Privacy Policy" intro="Effective September 1, 2026. This policy covers only the QueueMaster pilot under fourthcanal.com/queue.">
    <section><h2>Information we collect</h2><p>Lobby owners, admins, and staff candidates sign in through Fourth Canal&apos;s Google authentication. QueueMaster uses the profile ID, Google account name, and email needed to identify lobby membership and staff-promotion requests. Guests provide only a first name and desk or car location.</p></section>
    <section><h2>Guest session</h2><p>QueueMaster stores a random HttpOnly, SameSite=Lax browser cookie for up to 30 days so a guest can resume an active lobby. The database stores only a SHA-256 hash of that token, never the token itself.</p></section>
    <section><h2>How information is used</h2><ul><li>Operate the queue, display approved public guest fields, and keep views synchronized.</li><li>Authorize lobby owners, admins, staff candidates, and individual guests.</li><li>Record minimal queue transition events for safety and troubleshooting.</li></ul></section>
    <section><h2>Realtime privacy</h2><p>Realtime events contain only the lobby ID and revision. They do not contain names, emails, locations, guest tokens, session IDs, or promotion-request IDs. Clients refetch the snapshot they are authorized to see.</p></section>
    <section><h2>Retention</h2><p>Abandoned active entries expire after 12 hours; completed, cancelled, and no-show entries after 24 hours; guest sessions after 30 days. Closed staff candidate and promotion-request records are retained for 30 days. Operational backups may persist for the provider&apos;s normal backup window.</p></section>
    <section><h2>Services and future features</h2><p>QueueMaster uses Fourth Canal&apos;s existing Supabase authentication, database, and realtime services and its existing deployment. Billing, SMS, and analytics are not implemented in this pilot.</p></section>
    <section><h2>Questions</h2><p>Use the established Fourth Canal support contact for privacy questions. Do not submit medical, educational-record, or other sensitive information through lobby names or queue fields.</p></section>
  </QueueInformationPage>;
}

export function QueueTerms({ signedIn = false }: { signedIn?: boolean }) {
  return <QueueInformationPage signedIn={signedIn} eyebrow="Legal" title="QueueMaster Terms of Service" intro="Effective September 1, 2026. These pilot terms apply to use of QueueMaster under fourthcanal.com/queue.">
    <section><h2>Acceptance and pilot status</h2><p>By using QueueMaster, you agree to these terms. QueueMaster is a local pilot provided for evaluation and classroom workflow testing, without guaranteed availability or service levels.</p></section>
    <section><h2>Appropriate use</h2><p>Use QueueMaster only for lawful queue coordination. Do not enter protected health information, grades, confidential educational records, payment information, harassment, or misleading identity information.</p></section>
    <section><h2>Accounts and lobby responsibility</h2><p>Signed-in users are responsible for their Google account and for actions taken in lobbies they own or administer. Owners control staff promotion and must reassign active guests before removing an admin.</p></section>
    <section><h2>Guest and display information</h2><p>Guest first names and desk/car locations may appear on the public classroom display. Guests should use the minimum information needed to be found.</p></section>
    <section><h2>Unavailable features</h2><p>Pricing upgrades, payment processing, SMS notifications, and analytics exports are marked Coming soon and are not part of the pilot service.</p></section>
    <section><h2>Availability and changes</h2><p>Fourth Canal may change, pause, or end the pilot, remove abusive content, and adjust these terms as the product develops. Material changes will be reflected by a new effective date.</p></section>
    <section><h2>Disclaimer and limitation</h2><p>QueueMaster is provided as-is for workflow coordination. It is not an emergency, medical, attendance-compliance, or records-management system. To the extent permitted by law, Fourth Canal is not liable for indirect or consequential losses from use or unavailability of the pilot.</p></section>
  </QueueInformationPage>;
}
