-- Intentionally a no-op.
--
-- This draft was never applied. It replaced record_game_round with an older
-- Tooth Quest-only function, so applying it after newer game validation would
-- silently regress the live RPC. The forward-only replacement migration below
-- is the only migration that may be reviewed for application after preview QA.
